// Command room framing: for each topic, the problem the groups push back on (left side) and, for each main
// topic, the vision they are building (right side). A draft for the team to review, like the topic list itself.
// Keys are topic ids from public/topics.json (main topics, then "<main>/<sub-topic>").

export const PROBLEMS: Record<string, string> = {
  // main topics
  energy: "Dirty, unaffordable power",
  buildings: "Leaky, fossil-heated buildings",
  fossil: "Fossil fuel expansion & pollution",
  transport: "Car dependence & tailpipe emissions",
  waste: "Throwaway culture & plastic waste",
  health: "Toxic pollution in air, water & homes",
  water: "Polluted, threatened waters",
  nature: "Habitat loss & vanishing forests",
  food: "Fragile, industrial food systems",
  resilience: "Heat, floods & storms hitting unprepared places",
  local: "Community fragmentation & isolation",
  education: "Lack of climate education & awareness",
  policy: "Fossil-fuel-backed legislation & policy gridlock",
  justice: "Environmental injustice & racism",
  economy: "An extractive economy & insecure jobs",
  democracy: "Corporate & utility capture of democracy",
  movements: "War, exclusion & unmet community needs",
  broad: "The climate crisis (in general)",

  // sub-topics
  "energy/solar": "Slow solar build-out",
  "energy/wind": "Stalled offshore & onshore wind",
  "energy/community_power": "No say over where our power comes from",
  "energy/grid": "An outdated grid & runaway demand (incl. data centers)",
  "energy/utilities": "Rising rates & utility overreach",
  "energy/clean_energy": "Slow switch to renewable energy",
  "buildings/heat_pumps": "Homes heated with oil & gas",
  "buildings/efficiency": "Drafty, energy-wasting homes",
  "buildings/green_building": "High-carbon construction",
  "buildings/public_buildings": "Fossil-heated schools, town halls & places of worship",
  "fossil/gas_infra": "New gas pipelines & compressor stations",
  "fossil/gas_leaks": "Gas leaks & methane",
  "fossil/power_plants": "Fossil power plants & peakers",
  "fossil/biomass": "Wood-burning power plants",
  "fossil/nuclear": "Nuclear waste & risky plants",
  "fossil/fossil_general": "Fossil fuel dependence & unaccountable polluters",
  "transport/transit": "Unreliable, unaffordable transit",
  "transport/evs": "Gas-burning vehicles",
  "transport/active": "Streets that are unsafe to walk & bike",
  "transport/aviation": "Private jets & airport expansion",
  "transport/transport_general": "Car-first transportation planning",
  "waste/compost": "Food scraps sent to landfills",
  "waste/reuse": "Single-use stuff & things built not to last",
  "waste/plastics": "Plastic pollution",
  "waste/zero_waste": "Trash, litter & overflowing landfills",
  "health/air": "Dirty air",
  "health/toxics": "Toxic chemicals, lead & PFAS",
  "health/incinerators": "Incinerators & landfills next to neighborhoods",
  "health/climate_health": "Climate-driven illness & unhealthy homes",
  "water/rivers": "Polluted rivers & lakes",
  "water/sewage": "Sewage overflows & stormwater runoff",
  "water/drinking_water": "Unsafe or unaffordable drinking water",
  "water/coasts": "Threatened coasts, oceans & lost waterfront access",
  "nature/forests": "Logging & forest loss",
  "nature/urban_trees": "Treeless, overheated neighborhoods",
  "nature/land": "Development swallowing open land",
  "nature/wildlife": "Biodiversity loss",
  "nature/restoration": "Degraded habitat & invasive species",
  "nature/outdoors": "Unequal access to nature",
  "food/gardens": "Food deserts & no room to grow",
  "food/food_systems": "Hunger & struggling local farms",
  "resilience/heat": "Extreme heat",
  "resilience/flood": "Floods, storms & fragile infrastructure",
  "resilience/resilience_general": "Unprepared communities",
  "local/town_energy": "Towns without climate plans",
  "local/schools_campus": "Unsustainable schools & campuses",
  "local/faith": "Faith communities sitting out the climate crisis",
  "local/household": "High-carbon everyday living",
  "local/youth": "Young people shut out of decisions about their future",
  "local/business": "Business as usual",
  "education/k12": "Climate missing from the classroom",
  "education/awareness": "Silence & misinformation about climate",
  "education/arts": "A culture that looks away",
  "education/research": "Gaps in climate data & local knowledge",
  "policy/state_policy": "Weak or stalled state climate policy",
  "policy/federal_policy": "Federal & international rollback",
  "policy/local_policy": "Local rules that block climate action",
  "policy/ballot": "Fossil-funded ballot fights",
  "policy/budget": "Underfunded environmental agencies",
  "policy/bills": "Climate bills stuck or opposed",
  "justice/ej": "Pollution dumped on frontline communities",
  "justice/just_transition": "Transitions that leave workers & communities behind",
  "justice/racial_justice": "Racism",
  "justice/housing": "Displacement & unaffordable housing",
  "economy/green_jobs": "Too few good green jobs",
  "economy/labor": "Unsafe work & weak labor rights",
  "economy/economic_justice": "Inequality & an unfair tax system",
  "economy/finance": "Money flowing into fossil fuels",
  "democracy/democracy": "Opaque government & voter disempowerment",
  "democracy/money_politics": "Money in politics & utility influence",
  "movements/peace": "War, militarism & nuclear weapons",
  "movements/immigration": "Attacks on immigrants",
  "movements/indigenous": "Erasure of Indigenous peoples",
  "movements/wellbeing": "Unmet health & social needs",
  "broad/broad": "The climate crisis (in general)",
};

export const VISIONS: Record<string, string> = {
  energy: "Clean, fair power for all",
  buildings: "Healthy, efficient homes",
  fossil: "A fossil-free future",
  transport: "Clean ways to get around",
  waste: "A reuse economy",
  health: "Clean air & healthy communities",
  water: "Living rivers & coasts",
  nature: "Thriving forests & wild places",
  food: "Local, nourishing food",
  resilience: "Communities ready for what's coming",
  local: "Connected, acting communities",
  education: "A climate-literate public",
  policy: "Strong climate laws",
  justice: "Justice for frontline communities",
  economy: "Good green jobs & a fair economy",
  democracy: "People-powered democracy",
  movements: "Care, peace & belonging",
  broad: "A livable planet",
};

/** Strategies that confront a problem directly (the rest build something new). */
export const FIGHT_STRATEGIES = new Set(["policy_advocacy", "organizing", "electoral", "legal", "finance"]);
